version: '3.8'

services:
  db:
    image: postgres:13.1
    container_name: pg
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      # 初始化成功之后删除口令！
      POSTGRES_PASSWORD: password
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
      - log:/var/log/postgresql
      # https://hub.docker.com/_/postgres?tab=description
      - ./entrypoint-initdb.d:/docker-entrypoint-initdb.d
      # 执行上方自动初始化操作时先取消上方注销，并且注释掉下方所有挂接！
      # 执行完自动初始化操作后注释上方，取消下方注释！
      #- ./conf/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      #- ./conf/custom.conf:/var/lib/postgresql/data/custom.conf
    tmpfs:
      - /run/postgresql
      - /tmp
    shm_size: 4G

volumes:
  data:
  log:

