
services:
  plantuml:
    image: plantuml/plantuml-server
    container_name: plantuml
    restart: unless-stopped
    environment:
      TZ: 'Asia/Chongqing'
    ports:
      - 8085:8080
    tmpfs:
      - /tmp
    shm_size: 256M


