version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysqlabc123
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql/data
      - log:/var/log/mysql
    tmpfs:
      - /tmp
    shm_size: 2G

volumes:
  data:
  log:


