version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - 127.0.0.1:6379:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./.docker/redis/data/:/data
    tmpfs:
      - /tmp
    shm_size: 1G



# docker exec -t redis redis-cli PING

