version: '3.8'

services:
  db:
    image: postgres:16.1
    container_name: pg16
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - ./config.d:/etc/pg/conf.d
      - backup:/var/lib/postgresql/backup
      - data:/var/lib/postgresql/data
      - log:/var/log/postgresql
    tmpfs:
      - /tmp
    shm_size: 8G

volumes:
  backup:
  data:
  log:

