
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    # 如果需要rabbitmq持久化，则打开注释，会保存数据，重启镜像不会丢失
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq
      - ./.docker/rabbitmq/:/var/log/rabbitmq
    tmpfs:
      - /tmp
    shm_size: 1G



